name: Notifier

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            <b>${{ github.actor }}</b> opened 
            <a href="https://github.com/${{ github.repository }}/pulls">pull request</a> at
            <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            <pre>${{ github.event.commits[0].message }}</pre>